# Assignment

## Task-1

### Corpus

In [0]:
## SkLearn# Collection of string documents

corpus = [
     'this is the first document',
     'this document is the second document',
     'and this is the third one',
     'is this the first document',
]

### SkLearn Implementation

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectorizer.fit_transform(corpus)
skl_output = vectorizer.transform(corpus)

In [0]:
# sklearn feature names, they are sorted in alphabetic order by default.

print(vectorizer.get_feature_names())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


In [0]:
# Here we will print the sklearn tfidf vectorizer idf values after applying the fit method
# After using the fit function on the corpus the vocab has 9 words in it, and each has its idf value.

print(vectorizer.idf_)


[1.91629073 1.22314355 1.51082562 1.         1.91629073 1.91629073
 1.         1.91629073 1.        ]


In [0]:
# shape of sklearn tfidf vectorizer output after applying transform method.

skl_output.shape

(4, 9)

In [0]:
# sklearn tfidf values for first line of the above corpus.
# Here the output is a sparse matrix

print(skl_output[0])

  (0, 8)	0.38408524091481483
  (0, 6)	0.38408524091481483
  (0, 3)	0.38408524091481483
  (0, 2)	0.5802858236844359
  (0, 1)	0.46979138557992045


In [0]:
# sklearn tfidf values for first line of the above corpus.
# To understand the output better, here we are converting the sparse output matrix to dense matrix and printing it.
# Notice that this output is normalized using L2 normalization. sklearn does this by default.

print(skl_output[0].toarray())

[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


### custom implementation

In [0]:
def transform(dataset,vocab):
    rows = []
    columns = []
    values = []
    if isinstance(dataset, (list,)):
        for idx, row in enumerate(tqdm(dataset)): # for each document in the dataset
            # it will return a dict type object where key is the word and values is its frequency, {word:frequency}
            word_freq = dict(Counter(row.split()))
            # for every unique word in the document
            for word, freq in word_freq.items():  # for each unique word in the review.                
                if len(word) < 2:
                    continue
                # we will check if its there in the vocabulary that we build in fit() function
                # dict.get() function will return the values, if the key doesn't exits it will return -1
                col_index = vocab.get(word, -1) # retreving the dimension number of a word
                # if the word exists
                if col_index !=-1:
                    # we are storing the index of the document
                    rows.append(idx)
                    # we are storing the dimensions of the word
                    columns.append(col_index)
                    # we are storing the frequency of the word
                    values.append(freq)
        return csr_matrix((values, (rows,columns)), shape=(len(dataset),len(vocab)))
    else:
        print("you need to pass list of strings")


In [0]:
# Write your code here.
# Make sure its well documented and readble with appropriate comments.
# Compare your results with the above sklearn tfidf vectorizer
# You are not supposed to use any other library apart from the ones given below

from collections import Counter
from tqdm import tqdm
from scipy.sparse import csr_matrix
import math
import operator
from sklearn.preprocessing import normalize
import numpy as np
corpus = [
     'this is the first document',
     'this document is the second document',
     'and this is the third one',
     'is this the first document',
]
lista=[]
def fit(dataset):    
    unique_words = set() # at first we will initialize an empty set
    # check if its list type or not
    if isinstance(dataset, (list,)):
        for row in dataset: # for each review in the dataset
            for word in row.split(" "): # for each word in the review. #split method converts a string into list of words
                if len(word) < 2:
                    continue
                unique_words.add(word)
        unique_words = sorted(list(unique_words))
        vocab = {j:i for i,j in enumerate(unique_words)}
        
        dictii=[]
          
        for i in corpus:
            for j in i.split(" "):
                lista.append(j)
        lista.sort()
        dicti=Counter(lista)
        #print(dicti)
        count=0
        for k in dicti.values():
            count=count+k
        countr=0
        countf=[]
        listd=[]
        listc=[]
        tf=[]
        for i in corpus:
            for j in i.split(" "):
                countr=countr+1
            countf.append(countr)
            countr=0
            
        for i in corpus:
            for j in i.split(" "):
                listd.append(j)
                
            dictii.append(Counter(listd))
            listd.clear()
       
        for i in dictii:
            ra={}
            for k in i: 
                f=i[k]
                ra.update({k:f})
            tf.append(ra)
        #print(tf)
        #print(dictii)
     
        tf_rev=[]
        m=0
        for i in tf:
            
            rb={}
            for j in i:
                s=i[j]
                rb.update({j:(s/countf[m])})
                   
            tf_rev.append(rb)
            m=m+1
        #print(tf_rev)
                
        
            
            
       
        s=0
        listb=[]
        gb=[]
        n=len(corpus)
        for k,v in dicti.items():
            for i in corpus:
                g={}
                for j in i.split(" "):
                    if k in j:
                        s=s+1
                        break
                        
                    else:continue
                g.update({k:s})
            gb.append(g)
            listb.append(s)
            s=0
        s=list(dicti.keys())
        lists=(transform(corpus, vocab).toarray())
        print(s)
        print("\n")
        
        idf_dict={}
        for k in gb:
            for p,q in k.items():
                f=1+math.log((1+n)/(1+k[p]))
                idf_dict.update({p:f})
        #print(idf_dict)
        
        idf=[]
        for i in listb:
            f=1+math.log((1+n)/(1+i))
            idf.append(f)
        print(idf)
        print("\n")
        print(lists.shape)
        print("\n")
    
    #print(gb)
    
        
    fetch=[]
    for i in range(len(lists)):
        rq=[]
        for j in range(len(lists[i])):
            if lists[i][j]>0:
                     rq.append(s[j])
            else:
                 rq.append(0)
        fetch.append(rq)
    #print(fetch) 
    mn=[]
    countr=0
    for i in range(len(fetch)):
        
        for k in range(len(tf_rev)):
                mg=tf_rev[k]
                #print(mg)
                rc=[]
                for h,g in mg.items():
                   
                    #print(mg[h])
                    
                    for j in range(len(fetch[i])):
                        #print(fetch[i][j])
                        if fetch[i][j]==h:
                            rc.append(g)
                        
                        
                        
                mn.append(rc)
                
    #print(mn)
    pq=[]
    for i in range(len(fetch)):
        rd=[]
        for h,g in idf_dict.items():
            for j in range(len(fetch[i])):
                       # print(fetch[i][j])
                        if fetch[i][j]==h:
                            rd.append(g)
                        
                        
        pq.append(rd)
    #print(pq)
    res=[]
    for i in range(4):
        hg=[]
        for j in range(len(mn[i])):
            
            hg.append(mn[i][j]*pq[i][j])
        
        res.append(hg)
    #print(res)
    rb=[]
    for i in range(len(fetch)):
        for j in range(len(fetch[i])):
            if fetch[i][j]==0:
                #print(fetch.index(fetch[i][j]))
                res[i].insert(j,0)
    #print(res)
              
    
    ui=[]
    for i in res:
        
        rb=[i]
        ui.append(normalize(rb))
    
   # print(ui)
    for i in range(len(ui[0])):
        m=9
        for k in ui[0][i][::-1]:
            m=m-1
            if k>0:
                #m=list(ui[0][i]).index(k)
                print("({},{})  {}".format(0,m,k))
                print("\n")
    print(ui[0])
  
    return vocab 

vocab = fit(corpus)
#print(vocab)
#print(list(vocab.keys()))
lists=[]
lists=(transform(corpus, vocab).toarray())


#print(lists)

lists.shape

100%|██████████| 4/4 [00:00<00:00, 3991.72it/s]


['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


[1.916290731874155, 1.2231435513142097, 1.5108256237659907, 1.0, 1.916290731874155, 1.916290731874155, 1.0, 1.916290731874155, 1.0]


(4, 9)


(0,8)  0.3840852409148149


(0,6)  0.3840852409148149


(0,3)  0.3840852409148149


(0,2)  0.580285823684436


(0,1)  0.4697913855799205


[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


100%|██████████| 4/4 [00:00<00:00, 3996.48it/s]


(4, 9)

## Task-2

<font face='georgia'>
    <h4><strong>2. Implement max features functionality:</strong></h4>


In [0]:
# Below is the code to load the cleaned_strings pickle file provided
# Here corpus is of list type

import pickle
with open('cleaned_strings', 'rb') as f:
    corpus = pickle.load(f)
    
# printing the length of the corpus loaded
print("Number of documents in corpus = ",len(corpus))

Number of documents in corpus =  746


In [0]:
# Write your code here.
# Try not to hardcode any values.
# Make sure its well documented and readble with appropriate comments.

In [0]:
def transform2(dataset,vocab):
    rows = []
    columns = []
    values = []
    if isinstance(dataset, (list,)):
        for idx, row in enumerate(tqdm(dataset)): # for each document in the dataset
            # it will return a dict type object where key is the word and values is its frequency, {word:frequency}
            word_freq = dict(Counter(row.split()))
            # for every unique word in the document
            for word, freq in word_freq.items():  # for each unique word in the review.                
                if len(word) < 2:
                    continue
                # we will check if its there in the vocabulary that we build in fit() function
                # dict.get() function will return the values, if the key doesn't exits it will return -1
                col_index = vocab.get(word, -1) # retreving the dimension number of a word
                # if the word exists
                if col_index !=-1:
                    # we are storing the index of the document
                    rows.append(idx)
                    # we are storing the dimensions of the word
                    columns.append(col_index)
                    # we are storing the frequency of the word
                    values.append(freq)
        return csr_matrix((values, (rows,columns)), shape=(len(dataset),len(vocab)))
    else:
        print("you need to pass list of strings")


In [0]:
# Write your code here.
# Make sure its well documented and readble with appropriate comments.
# Compare your results with the above sklearn tfidf vectorizer
# You are not supposed to use any other library apart from the ones given below

from collections import Counter
from tqdm import tqdm
from scipy.sparse import csr_matrix
import math
import operator
from sklearn.preprocessing import normalize
import numpy as np
import pickle
with open('cleaned_strings', 'rb') as f:
    corpus2 = pickle.load(f)
    
# printing the length of the corpus loaded
print("Number of documents in corpus = ",len(corpus2))
lista=[]
def fit2(dataset):    
    unique_words = set() # at first we will initialize an empty set
    # check if its list type or not
    if isinstance(dataset, (list,)):
        for row in dataset: # for each review in the dataset
            for word in row.split(" "): # for each word in the review. #split method converts a string into list of words
                if len(word) < 2:
                    continue
                unique_words.add(word)
        unique_words = sorted(list(unique_words))
        vocab2 = {j:i for i,j in enumerate(unique_words)}
        
        dictii=[]
          
        for i in corpus2:
            for j in i.split(" "):
                lista.append(j)
        lista.sort()
        dicti=Counter(lista)
        #print(dicti)
        count=0
        for k in dicti.values():
            count=count+k
        countr=0
        countf=[]
        listd=[]
        listc=[]
        tf=[]
        for i in corpus2:
            for j in i.split(" "):
                countr=countr+1
            countf.append(countr)
            countr=0
            
        for i in corpus2:
            for j in i.split(" "):
                listd.append(j)
                
            dictii.append(Counter(listd))
            listd.clear()
       
        for i in dictii:
            ra={}
            for k in i: 
                f=i[k]
                ra.update({k:f})
            tf.append(ra)
        #print(tf)
        #print(dictii)
        tf_rev=[]
        m=0
        for i in tf:
            
            rb={}
            for j in i:
                s=i[j]
                rb.update({j:(s/countf[m])})
                   
            tf_rev.append(rb)
            m=m+1
        #print(tf_rev)
        gb=[]
        n=len(corpus2)
        listb=[]
        for k,v in dicti.items():
            for i in corpus2:
                g={}
                for j in i.split(" "):
                    if k in j:
                        s=s+1
                        break
                        
                    else:continue
                g.update({k:s})
            gb.append(g)
            listb.append(s)
            s=0
        
        
        #print(s)
        #print("\n")
        s=0
        listb=[]
        
        
        idf_dict={}
        for k in gb:
            for p,q in k.items():
                f=1+math.log((1+n)/(1+k[p]))
                idf_dict.update({p:f})
        #print(idf_dict)
        listi=[sorted(idf_dict.items(),key=lambda x:x[1],reverse=True)[:50]]
        print(listi)#both string and number
        #top 50 vocab
        vocab_50=[]#only strings
        for i in range(len(listi)):
            for j in range(len(listi[i])):
                vocab_50.append(listi[i][j][0])
        #print(vocab_50)
        unique_words_50 = set()
        unique_words_50 = sorted(list(vocab_50))
        #print(unique_words_50)
        j=i=1
        vocab2_50 = {j:i for i,j in enumerate(unique_words_50,start=0)}
        #print(vocab2_50)
        lists_50=(transform2(corpus2, vocab2_50).toarray())
        print(lists_50)
        print(lists_50.shape)
        rb=[]
        ui=[]
        for i in lists_50:
            rb=[i]
            ui.append(normalize(rb))
        #print(ui)
        
        print(ui[0][0])
        
        
        
        
        
    return vocab2

Number of documents in corpus =  746


In [0]:
vocab2 = fit2(corpus2)
#print(vocab2)
#print(transform(corpus2, vocab2_50).toarray())




[[('abandoned', 6.922918004572872), ('abroad', 6.922918004572872), ('abstruse', 6.922918004572872), ('academy', 6.922918004572872), ('accents', 6.922918004572872), ('accessible', 6.922918004572872), ('acclaimed', 6.922918004572872), ('accolades', 6.922918004572872), ('accurately', 6.922918004572872), ('achille', 6.922918004572872), ('ackerman', 6.922918004572872), ('adams', 6.922918004572872), ('added', 6.922918004572872), ('admins', 6.922918004572872), ('admiration', 6.922918004572872), ('admitted', 6.922918004572872), ('adrift', 6.922918004572872), ('adventure', 6.922918004572872), ('aesthetically', 6.922918004572872), ('affected', 6.922918004572872), ('affleck', 6.922918004572872), ('afternoon', 6.922918004572872), ('agreed', 6.922918004572872), ('aimless', 6.922918004572872), ('aired', 6.922918004572872), ('akasha', 6.922918004572872), ('alert', 6.922918004572872), ('alike', 6.922918004572872), ('allison', 6.922918004572872), ('allowing', 6.922918004572872), ('alongside', 6.9229180

100%|██████████| 746/746 [00:00<00:00, 24046.84it/s]


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(746, 50)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
