In [0]:
import numpy as np
import pandas as pd
#import plotly
#import plotly.figure_factory as ff
#import plotly.graph_objs as go
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
#from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
#init_notebook_mode(connected=True)

In [0]:
data = pd.read_csv('task_b.csv')
data=data.iloc[:,1:]
y = data['y'].values
X = data.drop(['y'], axis=1)

In [0]:
data.head()

f1            f2        f3    y
0  -195.871045 -14843.084171  5.532140  1.0
1 -1217.183964  -4068.124621  4.416082  1.0
2     9.138451   4413.412028  0.425317  0.0
3   363.824242  15474.760647  1.094119  0.0
4  -768.812047  -7963.932192  1.870536  0.0

In [0]:
print(data.corr()['y'])
#we can observe that f3 is more correlated to y than the other features


f1    0.067172
f2   -0.017944
f3    0.839060
y     1.000000
Name: y, dtype: float64


In [0]:
data.std()
#var(F2)>>var(F1)>data.std()>Var(F3)

f1      488.195035
f2    10403.417325
f3        2.926662
y         0.501255
dtype: float64

In [0]:
X=data[['f1','f2','f3']].values
Y=data['y'].values
print(X.shape)
print(Y.shape)

(200, 3)
(200,)


# What if our features are with different variance 

<pre>


> <b>Task1</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' and check the feature importance

> <b>Task2</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance

</pre>

In [0]:
from sklearn.model_selection import train_test_split
from sklearn import linear_model
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state=15)
clf = linear_model.SGDClassifier(eta0=0.0001, alpha=0.0001, loss='log', random_state=15, penalty='l2', tol=1e-3, verbose=2, learning_rate='constant')
clf.fit(X=X_train, y=y_train)
clf.coef_
#since feature f1 and f2 as high variance it as more negative weight compared to other features
#i.e.,var(F2)>>var(F1)>>Var(F3) implie Weight f2>weight f1>weight f3 before stanradization

-- Epoch 1
Norm: 0.64, NNZs: 3, Bias: -0.000451, T: 150, Avg. loss: 2519.859907
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 0.44, NNZs: 3, Bias: 0.000454, T: 300, Avg. loss: 3700.524704
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 1.61, NNZs: 3, Bias: -0.000646, T: 450, Avg. loss: 2668.580474
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 1.06, NNZs: 3, Bias: 0.000054, T: 600, Avg. loss: 2724.175085
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 1.46, NNZs: 3, Bias: -0.000546, T: 750, Avg. loss: 1659.479597
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 0.91, NNZs: 3, Bias: -0.001246, T: 900, Avg. loss: 3283.508318
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 1.14, NNZs: 3, Bias: -0.000546, T: 1050, Avg. loss: 2599.108764
Total training time: 0.00 seconds.
-- Epoch 8
Norm: 0.17, NNZs: 3, Bias: -0.000946, T: 1200, Avg. loss: 3587.171630
Total training time: 0.00 seconds.
-- Epoch 9
Norm: 0.67, NNZs: 3, Bias: -0.001746, T: 1350, Avg. loss: 3222.126803

array([[-0.03775828, -0.70442478,  0.16523703]])

In [0]:
from sklearn.model_selection import train_test_split
from sklearn import linear_model
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state=15)
clf = linear_model.SGDClassifier(eta0=0.0001, alpha=0.0001, loss='hinge', random_state=15, penalty='l2', tol=1e-3, verbose=2, learning_rate='constant')
clf.fit(X=X_train, y=y_train)
clf.coef_
#since feature f1 and f2 as high variance it as more  weight compared to other features
#i.e.,var(F2)>>var(F1)>>Var(F3) implie Weight f2>weight f1>weight f3 before stanradization

-- Epoch 1
Norm: 0.74, NNZs: 3, Bias: 0.000200, T: 150, Avg. loss: 2553.490327
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 0.73, NNZs: 3, Bias: 0.001100, T: 300, Avg. loss: 3545.641692
Total training time: 0.02 seconds.
-- Epoch 3
Norm: 1.57, NNZs: 3, Bias: 0.000000, T: 450, Avg. loss: 2801.806688
Total training time: 0.02 seconds.
-- Epoch 4
Norm: 0.82, NNZs: 3, Bias: -0.000300, T: 600, Avg. loss: 3235.468023
Total training time: 0.02 seconds.
-- Epoch 5
Norm: 1.48, NNZs: 3, Bias: -0.000800, T: 750, Avg. loss: 1732.864446
Total training time: 0.02 seconds.
-- Epoch 6
Norm: 0.97, NNZs: 3, Bias: -0.001500, T: 900, Avg. loss: 3282.645554
Total training time: 0.02 seconds.
-- Epoch 7
Norm: 1.41, NNZs: 3, Bias: -0.000700, T: 1050, Avg. loss: 2333.759393
Total training time: 0.02 seconds.
-- Epoch 8
Norm: 0.71, NNZs: 3, Bias: -0.001300, T: 1200, Avg. loss: 3395.312052
Total training time: 0.02 seconds.
-- Epoch 9
Norm: 0.89, NNZs: 3, Bias: -0.001500, T: 1350, Avg. loss: 3095.883588


array([[ 0.19738792, -0.72445957,  0.17001895]])

In [0]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import linear_model
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state=15)
clf = linear_model.SGDClassifier(eta0=0.0001, alpha=0.0001, loss='log', random_state=15, penalty='l2', tol=1e-3, verbose=2, learning_rate='constant')
scaler = StandardScaler()
X_std = scaler.fit_transform(X_train)
#Y_std = scaler.fit_transform( y_train)
clf.fit(X=X_std, y=y_train)
clf.coef_

#since feature f1 and f2 as high variance compared to f3 after standarization its weight reduced compared to  feature f3
#i.e.,var(F2)>>var(F1)>>Var(F3) implie Weight f2<weight f1<weight f3 after stanradization

-- Epoch 1
Norm: 0.01, NNZs: 3, Bias: -0.000000, T: 150, Avg. loss: 0.691900
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 0.01, NNZs: 3, Bias: -0.000000, T: 300, Avg. loss: 0.689318
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 0.02, NNZs: 3, Bias: -0.000001, T: 450, Avg. loss: 0.686755
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 0.02, NNZs: 3, Bias: -0.000001, T: 600, Avg. loss: 0.684213
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 0.03, NNZs: 3, Bias: -0.000001, T: 750, Avg. loss: 0.681690
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 0.04, NNZs: 3, Bias: -0.000001, T: 900, Avg. loss: 0.679187
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 0.04, NNZs: 3, Bias: -0.000002, T: 1050, Avg. loss: 0.676702
Total training time: 0.00 seconds.
-- Epoch 8
Norm: 0.05, NNZs: 3, Bias: -0.000001, T: 1200, Avg. loss: 0.674237
Total training time: 0.00 seconds.
-- Epoch 9
Norm: 0.06, NNZs: 3, Bias: -0.000001, T: 1350, Avg. loss: 0.671791
Total training time: 0.0

array([[0.05514966, 0.00320732, 0.68086063]])

In [0]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import linear_model
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state=15)
clf = linear_model.SGDClassifier(eta0=0.0001, alpha=0.0001, loss='hinge', random_state=15, penalty='l2', tol=1e-3, verbose=2, learning_rate='constant')
scaler = StandardScaler()
X_std = scaler.fit_transform(X_train)
#Y_std = scaler.fit_transform( y_train)
clf.fit(X=X_std, y=y_train)
clf.coef_
#since feature f1 and f2 as high variance compared to f3 after standarization its weight reduced compared to  feature f3
#i.e.,var(F2)>>var(F1)>>Var(F3) implie Weight f2<weight f1<weight f3 after stanradization

-- Epoch 1
Norm: 0.01, NNZs: 3, Bias: 0.000000, T: 150, Avg. loss: 0.994997
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 0.02, NNZs: 3, Bias: -0.000000, T: 300, Avg. loss: 0.984591
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 0.04, NNZs: 3, Bias: -0.000000, T: 450, Avg. loss: 0.974185
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 0.05, NNZs: 3, Bias: 0.000000, T: 600, Avg. loss: 0.963779
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 0.06, NNZs: 3, Bias: 0.000000, T: 750, Avg. loss: 0.953374
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 0.07, NNZs: 3, Bias: 0.000000, T: 900, Avg. loss: 0.942968
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 0.09, NNZs: 3, Bias: 0.000000, T: 1050, Avg. loss: 0.932562
Total training time: 0.00 seconds.
-- Epoch 8
Norm: 0.10, NNZs: 3, Bias: -0.000000, T: 1200, Avg. loss: 0.922156
Total training time: 0.00 seconds.
-- Epoch 9
Norm: 0.11, NNZs: 3, Bias: -0.000000, T: 1350, Avg. loss: 0.911750
Total training time: 0.01 sec

array([[0.0705479 , 0.05549049, 0.99391018]])